// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requirement.proto

package grpc;

import com.google.protobuf.ByteString;

/**
 * Response message interface.
 * @author protocol buffer compiler
 */
public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    ByteString getTypeBytes();

    /**
     * <code>string reqJson = 2;</code>
     * @return The reqJson.
     */
    String getReqJson();
    /**
     * <code>string reqJson = 2;</code>
     * @return The bytes for reqJson.
     */
    ByteString getReqJsonBytes();
}
