// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package grpc;

/**
 * @author Guo Weize
 * @date 2021/5/5
 */
public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
